window:
  dimensions:
    columns: 70
    lines: 21
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  decorations: none
scrolling:
  history: 10000
  multiplier: 11
background_opacity: 0
window.dynamic_title: false
env:
  WINIT_X11_SCALE_FACTOR: "1.0"
font:
  normal:
    family: MesloLGS NF
    style: SemiBold
  bold:
    family: JetBrains Mono
  italic:
    family: JetBrains Mono
  offset:
    x: 0
    y: 0
  size: 13

hide_cursor_when_typing: true
cursor:
  style: Block
  unfocused_hollow: true

